version: "3.8"

services:
  rabbitmq:
    image: rabbitmq:management
    hostname: rabbitmq
    restart: "always"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - 5672:5672
      - 15672:15672
