version: "3.8"

services:
  rabbitmq:
    image: rabbitmq:management
    hostname: rabbitmq
    restart: "always"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
        - ./data/:/var/lib/rabbitmq/
        - ./log/:/var/log/rabbitmq/
    ports:
      - 5672:5672
      - 15672:15672